### ISSUE TITLE
Support Action Name in Typescript SetState

### ISSUE THREAD

**Issue by WaleedZ90** [pmndrs/zustand#980] opened 2022-05-31 14:42 UTC
It came to our attention that the SetStateType action name is not defined in `zustand/src/vanilla.d.ts`.
Even though it's written in the [documentation](https://github.com/pmndrs/zustand#logging-actions) 

Suggestion to add the definition of the actionName to the type

**Comment by dai-shi** [comment] 2022-05-31 22:43
Vanilla store doesn't support action name. It's only available when you use `devtools` middleware. Types work magically when you add the middleware. Please also refer `tests/middlewareTypes.test.tsx` for working examples. There might be a bug, so if you seem to find one, please provide a reproduction. Thanks.

**Comment by dai-shi** [comment] 2022-06-01 09:22
Is this issue about `devtools` or just `vanilla`?

We have types for `devtools` here, overloading the one in `vanilla`.
https://github.com/pmndrs/zustand/blob/89c35772cfe99d70a05293aa34295ea59536cf3f/src/middleware/devtools.ts#L53-L55

`vanilla` doesn't support action names in JS, so we shouldn't add types for 3rd argument in TS.

**Comment by dai-shi** [comment] 2022-06-06 22:37
That looks like a case with `devtools`.

Can anyone open a new issue with a reproduction with typescript playground?



> It came to our attention that the SetStateType action name is not defined in `zustand/src/vanilla.d.ts`.

It's very intentional, so not an issue. Closing this.

**Closed by dai-shi** 2022-06-06 22:37 UTC

**Comment by hasan-almujtaba** [comment] 2022-06-21 12:51
Hello i following this [Typescript Example](https://codesandbox.io/s/nostalgic-voice-3knvd?file=/src/App.js) for creating separated splices. It gave me error like ```Expected 1-2 arguments, but got 3``` from ```SetState``` type. I'm using it in [this repository](https://github.com/hasan-Almujtaba/next-starter).

**Comment by dai-shi** [comment] 2022-06-21 13:07
https://github.com/hasan-almujtaba/next-starter/blob/10ade3d52a2a0eba949de03215b7e7545dcc498d/store/example.ts#L7
It's when you add more arguments in `set`?
It's because the types in L4 only accepts 1-2 arguments.

You need to type function by yourself, if inline function doesn't work for you.
```ts
const createExample = (set: (partial: (state: Store) => Partial<Store>, replace?: boolean, name?: string) => void, get: GetState<Store>) => ({
  count: 0,
  increment: () => {
    set((prev) => ({ count: prev.count + 1 }))
  },
})
```
Hope it works.

**Comment by devanshj** [comment] 2022-06-21 15:46
If one follows [these intructions given in the docs for slices pattern](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#independent-slices-pattern) one'd have no problems. In particular this instruction:

> If you have some middlewares then replace `StateCreator<MySlice, [], []>` with `StateCreator<MySlice, Mutators, []>`. Eg if you're using devtools then it'll be `StateCreator<MySlice, [["zustand/devtools", never]], []>`.

Following those instructions would lead to the following code, which I think is the one that is being desired...

```ts
import create, { StateCreator } from 'zustand'
import { devtools } from "zustand/middleware"

interface BearSlice {
  bears: number
  addBear: () => void
}
const createBearSlice: StateCreator<BearSlice, [["zustand/devtools", never]], []> = (set) => ({
  bears: 0,
  addBear: () => set((state) => ({ bears: state.bears + 1 }), false, "addBear"),
})

const useStore = create<BearSlice>()(devtools((...a) => ({
  ...createBearSlice(...a)
})))
```

It's recommended to consult the docs before reporting an issue :)

> Hello i following this [Typescript Example](https://codesandbox.io/s/nostalgic-voice-3knvd?file=/src/App.js) for creating separated splices.

I guess this sandbox is from the wiki? So I guess the issue here was that the old docs in the wiki were consulted instead of new ones. @dai-shi could you delete or redirect outdated wikis to new docs?

Zustand has complex types internally so that there are no complex types externally on users end. If one follows the docs one'd find one has to annotate and type so little. See #710 if you want to learn about the complex internal types.

**Comment by hasan-almujtaba** [comment] 2022-06-21 18:50
> https://github.com/hasan-almujtaba/next-starter/blob/10ade3d52a2a0eba949de03215b7e7545dcc498d/store/example.ts#L7 It's when you add more arguments in `set`? It's because the types in L4 only accepts 1-2 arguments.
> 
> You need to type function by yourself, if inline function doesn't work for you.
> 
> ```ts
> const createExample = (set: (partial: (state: Store) => Partial<Store>, replace?: boolean, name?: string) => void, get: GetState<Store>) => ({
>   count: 0,
>   increment: () => {
>     set((prev) => ({ count: prev.count + 1 }))
>   },
> })
> ```
> 
> Hope it works.

Thanks for your suggestion, it's work as expected.

**Comment by devanshj** [comment] 2022-06-21 19:12
> i'm following sandbox from this wiki

Yeah I guessed that, no problems, it's our bad that we forgot to redirect the outdated wiki to new docs.

**Comment by hasan-almujtaba** [comment] 2022-06-21 21:10
Got it, thanks!

**Comment by dai-shi** [comment] 2022-06-22 00:16
> could you delete or redirect outdated wikis to new docs?

Done.

**Comment by hasan-almujtaba** [comment] 2022-07-10 02:08
> Yeah that's a bit of a limitation, instead of writing `["zustand/persist", Example]` write `["zustand/persist", unknown]`, like so: https://tsplay.dev/w1PnAW.
> 
> It won't make much of a difference, as you can see `useStore` still has the correct type ie `StorePersist<BearSlice, Partial<BearSlice>>` it's only the store received as parameter has `StorePersist<BearSlice, unknown>`.
> 
> The second type parameter is for the partialised state, so unless you're using redefining options with `store.persist.setOptions({ partialize: ... })` it doesn't affect you.

Hello, how to do indepent slice like this with persist and devtools middleware like this? here my example, this example give me error https://tsplay.dev/wXQAON

**Comment by devanshj** [comment] 2022-07-10 11:22
That too is a (recently) known issue, see https://github.com/pmndrs/zustand/issues/1046#issuecomment-1175333987 for a temporary fix. It probably will be fixed in next rc.

**Comment by hasan-almujtaba** [comment] 2022-07-11 08:52
> That too is a (recently) known issue, see [#1046 (comment)](https://github.com/pmndrs/zustand/issues/1046#issuecomment-1175333987) for a temporary fix. It probably will be fixed in next rc.

I see, currently i try using [interdependent slices](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#interdependent-slices-pattern) and it's works as expected so for now i'm going to use this instead.

**Comment by Mugilan-Codes** [comment] 2023-12-24 04:52
I am trying this as well. How to set only one slice to persist when using the slices pattern though?

**Comment by dbritto-dev** [comment] 2023-12-24 04:57
> I am trying this as well. How to set only one slice to persist when using the slices pattern though?

@Mugilan-Codes you can use `partialize`
