### ISSUE TITLE
store.setState() api method doesn't trigger persistance

### ISSUE THREAD

**Issue by pauliusef** [pmndrs/zustand#238] opened 2020-11-09 21:22 UTC
I'm trying to use persistance middleware in React, however I'm doing store updates from outside a react component by calling `useStore.setState({ property: value })`. This function call sets the state and appears in Redux devtools without persisting the update in `localStorage`.

**Comment by dai-shi** [comment] 2020-11-10 02:01
Right, currently it's only patching `set` in store creator.

@AnatoleLucet thoughts?

**Comment by AnatoleLucet** [comment] 2020-11-10 08:30
I'm not sure. We'll definitely need to modify some bits in `vanilla.ts -> create()`. An option would be to modify the store's internal api object via the middleware (same thing as `set`) and then use it in `create()`. But I'm not sure how this could be done, I'll check later in the day.

**Comment by dai-shi** [comment] 2020-11-10 08:48
Yeah, I think that's only the option.

`devtools` middleware has this code:
```ts
    const savedSetState = api.setState
    api.setState = (state: PartialState<S>, replace?: boolean) => {
      savedSetState(state, replace)
      api.devtools.send(api.devtools.prefix + 'setState', api.getState())
    }
```

I'm pretty sure if there's just one `persist` middleware alone, it works fine. When we chain multiple middleware, we need to be careful.

**Comment by AnatoleLucet** [comment] 2020-12-10 14:04
@dai-shi @pauliusef I think this issue can be closed now that #251 is merged.

**Comment by dai-shi** [comment] 2020-12-10 14:21
Yeah, thanks!

**Closed by dai-shi** 2020-12-10 14:21 UTC

**Comment by pauliusef** [comment] 2020-12-10 14:39
Thank you, will update and test it out!

**Comment by dai-shi** [comment] 2020-12-10 14:48
(Sorry, it's not released yet. You can try the codesandbox build in the PR, though.

**Comment by arryanggaputra** [comment] 2020-12-12 10:57
Is there any way to exclude some key from persist?

**Comment by dai-shi** [comment] 2020-12-12 11:03
#254 is merged, but we are still discussing the overall design in #248. I would like to hold on releasing before we decide our plan.

**Comment by arryanggaputra** [comment] 2020-12-12 11:06
@dai-shi  it's weird, store.setState actually persistent.

**Comment by dai-shi** [comment] 2020-12-12 12:07
Isn't it because you use `set` from the create callback function?

**Comment by arryanggaputra** [comment] 2020-12-12 13:05
@dai-shi  no, I'm using `store.setState` . This is how I define the store

```typescript
export const _accountDataStore = create(
  persist<TAccountDataStore>(
    (set, get) => ({
      accountData: get()?.accountData || null,
      setAccountData: (data) => set({accountData: data}),
      removeAccountData: () => set({accountData: null}),
    }),
    {
      name: 'sharpmenu-account', // unique name
      storage: AsyncStorage, // (optional) default is 'localStorage'
    },
  ),
);

```

I set store for temporary purpose by using `_accountDataStore.setState({accountData: {foo:'bar'}})`, and it's persist.

**Comment by dai-shi** [comment] 2020-12-12 23:15
hmmm, I don't know why..

**Comment by AnatoleLucet** [comment] 2020-12-12 23:27
@arryanggaputra do you mean with the current version of zustand (v3.2.0)?

**Comment by arryanggaputra** [comment] 2020-12-13 00:18
@AnatoleLucet  I'm using `^3.2.0` in `react-native` with `AsyncStorage`

**Comment by AnatoleLucet** [comment] 2020-12-13 00:46
@arryanggaputra I'm unable to reproduce this. Can you please share a codesandbox or a github repo where your issue happens? 🙏
