### ISSUE TITLE
Zustand persist with AsyncStorage

### ISSUE THREAD

**Issue by Ross249** [pmndrs/zustand#1483] opened 2022-12-15 11:29 UTC
## Summary
When i use zustand persist on react native, i found the nested **actions** can  not be persisted.

I use **useCommonActions** , **actions** are undefined.

## Link to reproduction
``` 
import create from "zustand";
import { persist } from "zustand/middleware";
import AsyncStorage from "@react-native-async-storage/async-storage";

export const useCommonStore = create(
  persist(
    (set, get) => ({
      token: "1",
      isIntro: false,
      phone: "56782345",
      avatar: "",
      galleryPermission: false,
      profile: {
        UserName: "",
        FirstName: "",
        SecondName: "",
        Description: "",
      },
      actions: {
        setToken: (token) => set((state) => ({ token: token })),
        setPhone: (newPhone) => set(() => ({ phone: newPhone })),
        setAvatar: (newAvater) => set(() => ({ avatar: newAvater })),
        setProfile: (newProfile) => set(() => ({ profile: newProfile })),
        setIsIntro: (isIntro) => set(() => ({ isIntro: isIntro })),
        setGalleryPermission: (newPermission) =>
          set(() => ({ galleryPermission: newPermission })),
      },
    }),
    { name: "common-storage", getStorage: () => AsyncStorage }
  )
);

export const useCommonActions = () => useCommonStore((state) => state.actions);
```

**Comment by dai-shi** [comment] 2022-12-15 11:43
Duplicate of #1481.

**Closed by dai-shi** 2022-12-15 11:43 UTC
