### ISSUE TITLE
Zustand 3.5.8 broke next.js with webpack 5.

### ISSUE THREAD

**Issue by MarkLyck** [pmndrs/zustand#534] opened 2021-08-14 16:14 UTC
I'm using next.js with zustand for state management.

I'm not sure what's in the `3.5.8` version of this package. But when I upgraded from 3.5.7 to 3.5.8 every single page I have is broken in development / hot reloading mode.

I'm getting a completely unrelated error that makes it look like it's a problem with my component imports.

```
Server Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

^ Red herring.

Note: If I make a production build everything works as expected and there are no errors. The errors only occur when I run `next` in development / hot reloading mode with webpack 5.

After spending hours trying to fix what looked to be random new problems with circular dependencies that was introduced by upgrading zustand somehow. I made it to a component where the only thing that was wrong with it, or broke it was importing `useStore` from zustand...

At that point I realized it wasn't so much a component issue. But something introduced by Zustand.

I checked the release note of the latest version and it says:

```
#507 fix(build): Improved ESM support for most used bundlers with fallbacks for older bundlers
```

And suddenly it all makes sense. I'm no expert in bundlers, but this "improved ESM support"  to zustand must have caused a change in how next.js handles my files, and broken not just the zustand useStore I have, but also created circular dependencies issues.

It definitely does not seem to be compatible with 3.5.7 for me.

My next.config.js file is pretty simple:

```
const withAntdLess = require('next-plugin-antd-less')
const { withPlausibleProxy } = require('next-plausible')

module.exports = withPlausibleProxy()(
  withAntdLess({
    modifyVars: { '@primary-color': '#3366ff' },
    lessVarsFilePathAppendToEndOfContent: false,
    cssLoaderOptions: {},

    webpack(config) {
      return config
    },
  })
)
```

And here is my `.babelrc`

```
module.exports = {
  presets: [['next/babel']],
  plugins: [['import', { libraryName: 'antd', style: true }]],
}
```

I'm using `"next": "11.1.0",` with webpack 5 enabled.

I hope you can help figure out either what went wrong with Zustand in this patch update. Or if I need to make some changes to my project to support future versions of zustand. (I love this state management library, it's amazing!)

For now the only change I made to get it to work again was downgrading to 3.5.7

**Comment by barelyhuman** [comment] 2021-08-14 16:27
@MarkLyck is it possible for you to create reproduction of the same? like a repo that we can use to dig deeper on this?

**Comment by MarkLyck** [comment] 2021-08-14 16:37
@barelyhuman I'd be happy to provide you access to my repo to reproduce the issue if that helps.

It's here: https://github.com/MarkLyck/formula-stocks

To reproduce the issue you can clone the repo and run this command line:

```
git checkout tags/v1.0.323 && rm -rf node_modules && rm -rf yarn.lock && yarn && yarn dev
```

Then open `localhost:3000` in your browser and you will see the error above.

Or just upgrade zustand to 3.5.8 on the `main` branch and run `yarn && yarn dev`

- Sorry, I don't have time to provide a minimal reproducible project (at least not right now, I'm a bit behind on schedule)

**Comment by barelyhuman** [comment] 2021-08-14 16:42
@MarkLyck  that works, I'll update you with the needed fix in a bit

**Comment by barelyhuman** [comment] 2021-08-14 17:37
@MarkLyck could you try using the below version and confirm that it works?
```
yarn add https://pkg.csb.dev/barelyhuman/zustand/commit/76d40ffb/zustand
npm i https://pkg.csb.dev/barelyhuman/zustand/commit/76d40ffb/zustand
```

@dai-shi https://github.com/barelyhuman/zustand/pull/4 for you to refer the change that was made

**Comment by MarkLyck** [comment] 2021-08-14 17:43
@barelyhuman I can confirm that package works perfectly fine! 👏 No errors :)

**Comment by dai-shi** [comment] 2021-08-15 00:03
wow, it's very nice to see you guys fix it so quickly.



> @dai-shi [barelyhuman#4](https://github.com/barelyhuman/zustand/pull/4) for you to refer the change that was made

Hm, it doesn't seem an ideal solution for a long run because it's officially marked as deprecated. Do we have a better idea, or it can't be helped?

I'm not sure if I understand it correctly, but if `"./": "./"` works, it means webpack 5 picks the CJS build, right?

**Comment by barelyhuman** [comment] 2021-08-15 00:18
https://nodejs.org/api/packages.html#packages_subpath_patterns 
This isn't deprecated, only the `/` is , i'm using a proper glob which matches the above. 

> it means webpack 5 picks the CJS file, right ?

I'm not sure, so while I was experimenting with the given repo, i was modifying the actual esm folder index and the changes were getting reflected but I'm guessing something else is blocking this on the deeper level, while this solves, I'll have to go deeper to find the reasoning. 

The above was just to avoid @MarkLyck from having to wait long before his project starts working again.

**Comment by dai-shi** [comment] 2021-08-15 00:28
> https://nodejs.org/api/packages.html#packages_subpath_patterns
> This isn't deprecated, only the `/` is , i'm using a proper glob which matches the above.

@barelyhuman my apologies. that was my mistake of the diff. you are absolutely right on this.

**Comment by dai-shi** [comment] 2021-08-15 01:11
I'm trying to check my hypothesis, but failed to repro the discussion here. I clone the repo and checked out `tags/v1.0.324`, which reproduced the error. But, adding `"./*": "./*"` in node_modules/zustand/package.json doesn't fix. I also tried `yarn add https://pkg.csb.dev/barelyhuman/zustand/commit/76d40ffb/zustand` which doesn't help. I feel like I'm missing something.

**Comment by barelyhuman** [comment] 2021-08-15 03:59
You’ll have to force reload to see the effect, i was restarting the server altogether to see it reflect what I was doing

**Comment by dai-shi** [comment] 2021-08-15 10:42
```bash
git clone https://github.com/MarkLyck/formula-stocks.git
cd formula-stocks
yarn
yarn add https://pkg.csb.dev/barelyhuman/zustand/commit/76d40ffb/zustand
yarn dev
```

I did this ☝️  from scratch, but it shows the error.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/490574/129475691-2101f14a-31de-4101-8274-d261de91cc21.png">

Any hint to make it work is appreciated.

**Comment by MarkLyck** [comment] 2021-08-15 12:18
@dai-shi you might need to remove the existing `yarn.lock` file and or `node_modules`

**Closed** 2021-08-17 11:42 UTC

**Comment by dai-shi** [comment] 2021-08-17 12:07
https://github.com/pmndrs/zustand/releases/tag/v3.5.9 is released.
If anyone faces any issue, please open a new issue.
