### ISSUE TITLE
Functions aren't stored in persited store

### ISSUE THREAD

**Issue by andre-lergier** [pmndrs/zustand#652] opened 2021-11-10 21:42 UTC
I use Zustand to save individual cookie settings in my Next.js app.

When I initially load the application (after deleting the Local Storage) everything is working fine and I can execute the `apply`-function on every object of my `settings` array.

Later when I reload the page, I get an error that `apply` doesn't exist and isn't a function. If I check the stored data in my Local Storage I can see, that everything is stored fine but the key `apply` is missing in every object.

Do you have any idea how I could fix this? Or is this a bug in this library?

---

Code of the Store:
```js
const useCookieStore = create(
  persist(
    (set) => ({
      saved: false,
      settings: [
        {
          name: 'cookieAnalytics',
          title: 'Analytics',
          state: true,
          apply: (setting) => {
            console.log('apply Analytics');
          },
        },
        {
          name: 'cookieLiveChat',
          title: 'Live Chat',
          state: true,
          apply: (setting) => {
            console.log('apply Chat');
          },
        },
      ],
      updateSavedState: () => set(() => ({ saved: true })),
      updateSettings: (name) =>
        set((state) => ({
          settings: state.settings.map((el) => {
            return el.name === name ? { ...el, state: !el.state } : { ...el };
          }),
        })),
    }),
    {
      name: 'mt-cookie-settings',
    }
  )
);
```

Applying the settings:
```js
const settings = useCookieStore((state) => state.settings);

const applySettings = () => {
  settings.forEach((setting) => setting.apply(setting));
};
```

**Comment by AnatoleLucet** [comment] 2021-11-10 22:13
Hi :wave:, this is pretty much a duplicate of #457. The `apply` functions are not present after hydration for the same reason as #618.

One way to fix your issue would be to give a custom deep merge function to persist. See [the doc](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#merge) for more details.

**Closed by AnatoleLucet** 2021-11-10 22:13 UTC

**Comment by mohamed-younes16** [comment] 2023-09-01 07:20
it worked

**Comment by hsavit1** [comment] 2024-08-18 15:49
is this still the recommended technique?
