### ISSUE TITLE
Insanely poor scene performance in demo

### ISSUE THREAD

**Issue by Michael77** [pmndrs/zustand#1988] opened 2023-08-10 22:56 UTC
## Summary

Your project looks cool, but when I visit the demo at https://zustand-demo.pmnd.rs/ it almost bricks my entire browser. From what I can see this is very likely due to the expensive animated scene serving as the background.

```
Chromium Version 114.0.5735.198 (Official Build) Arch Linux (64-bit)
NVIDIA GeForce RTX 2060

Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Canvas out-of-process rasterization: Disabled
Direct Rendering Display Compositor: Disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
OpenGL: Disabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Video Decode: Software only. Hardware acceleration disabled
Video Encode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable
WebGPU: Disabled
```

## Link to reproduction

https://zustand-demo.pmnd.rs/

**Comment by chrisk-7777** [comment] 2023-08-11 07:27
Thanks for the issue @Michael77 - out of interest, what is the performance like for the examples on the react three fiber page: https://docs.pmnd.rs/react-three-fiber/getting-started/examples

@dai-shi - we could possibly introduce a [prefers-reduced-motion flag](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) and present a still image for those users with the flag on?

**Comment by dai-shi** [comment] 2023-08-11 13:00
@chrisk-7777 Yeah, feel free to draft a PR.

**Comment by Michael77** [comment] 2023-08-11 16:27
@chrisk-7777 The [monitors](https://codesandbox.io/s/bst0cy) scene gets maybe 0.2 fps and [bananas](https://codesandbox.io/s/2ycs3) comes pretty close to 1 fps.

Non-webgl based animations such as [anime.js](https://animejs.com/) easily go above 60 fps on my system.

**Comment by chrisk-7777** [comment] 2023-08-12 02:38
Thanks @Michael77 - I'll get the above PR organised, but I don't think it will help with the root cause of your performance issues. 

You may need to raise an issue with https://github.com/pmndrs/react-three-fiber/

I'm not super across that project, but I do work with canvas/webgl quite a bit, and this line in your output above `Software only, hardware acceleration unavailable` seems interesting. 

Can you try enable it? 

- From the upper-right corner of your Chrome browser, click the three dots icon.
- Select Settings, then System.
- Enable Use hardware acceleration when available.

**Comment by Michael77** [comment] 2023-08-12 03:34
@chrisk-7777 I've fiddled around with `chrome://flags` in an attempt to enable hardware rendering, but it seems that Nvidia doesn't support Linux very well, which in turn causes webgl based sites to perform very poorly.

Hopefully webgpu will fix these problems.

**Comment by chrisk-7777** [comment] 2023-09-13 02:13
It sounds like it was isolated to a specific OS? But thanks for letting us know. 

I didn't get around to the MR for "reduced motion" flag, but it would not have addressed the core problem anyway. 

I'm going to close this issue off, but do let us know if you run into other issues

**Closed by chrisk-7777** 2023-09-13 02:13 UTC
