### ISSUE TITLE
v4 Partialize TS Issues

### ISSUE THREAD

**Issue by charkour** [pmndrs/zustand#1134] opened 2022-07-26 00:57 UTC
Hi. Thank you for this great package. 

I am using v4 RC 4 and am having TS issues when using the persist middleware with the partialize method. 

I've attached a [code sandbox](https://codesandbox.io/s/heuristic-rain-swytsd?fontsize=14&hidenavigation=1&theme=dark) with a reproductino of the issue. If you comment line 25, the types are fine. What's the recommended way of using partialize with Typescript in v4?

Here is the same [code working with zustand v3.7.2](https://codesandbox.io/s/mystifying-cartwright-8m61rw?file=/src/App.tsx).

Thank you!

**Comment by dai-shi** [comment] 2022-07-26 01:15
Duplicate of #1127.
https://codesandbox.io/s/ecstatic-booth-hhi126

https://github.com/pmndrs/zustand/issues/1127#issuecomment-1193922792 If you have a suggestion to improve the docs, it's much appreciated.

**Closed by dai-shi** 2022-07-26 01:15 UTC

**Comment by charkour** [comment] 2022-07-26 01:28
Thank you, sorry I missed the updated syntax. 

I'll take a look and see if the docs can be updated.

**Comment by charkour** [comment] 2022-07-26 01:41
> https://github.com/pmndrs/zustand/issues/1127#issuecomment-1193922792 If you have a suggestion to improve the docs, it's much appreciated.

I've made a simple PR that mirrors the root readme: https://github.com/pmndrs/zustand/pull/1136. Please let me know if you have any feedback. Thank you!
