### ISSUE TITLE
useStore.subscribe hook does not correctly infer type from selector

### ISSUE THREAD

**Issue by disambiguator** [pmndrs/zustand#331] opened 2021-03-18 06:47 UTC
Demonstrated in this codesandbox: https://codesandbox.io/s/angry-pare-zndc9?file=/src/App.tsx:321-339

When using useStore.subscribe, the argument to the listener function is getting inferred as unknown, even though it should be using the return type from the selector function.

**Comment by dai-shi** [comment] 2021-03-18 07:43
I'm not sure if I understand the question correctly, because the codesandbox doesn't contain `useStore.subscribe`.

https://codesandbox.io/s/hungry-chatterjee-53zxo
This is what I modified. I think this is because of stricter typing in v3.3.3.

**Comment by disambiguator** [comment] 2021-03-18 19:26
@dai-shi I'm very sorry - forgot to press save in codesandbox :|. The link should show you the type error now.

**Comment by dai-shi** [comment] 2021-03-19 03:34
I see.
@TkDodo Can you help?

**Comment by TkDodo** [comment] 2021-03-19 11:34
@dai-shi I downgraded the example to `3.0.0`, and it also doesn't work for me there, so at least it's not a regression. could it be that this hasn't worked from the beginning?

looking a the types, the correlation seems to be there, and also the type inference looks correct when inspecting:

```
<number>(listener: StateSliceListener<number>, selector: StateSelector<State, number>, equalityFn?: EqualityChecker<number> | undefined) => () => void
```

if you change `(foo)` to `(foo: string)` in the selector, you will also get a type-error, because `number` is expected.

doing `useStore.subscribe<number>` also works, so I have really no clue at the moment where the undefined is coming from :(

**Comment by dai-shi** [comment] 2021-03-19 12:29
> @dai-shi I downgraded the example to `3.0.0`, and it also doesn't work for me there, so at least it's not a regression. could it be that this hasn't worked from the beginning?

@TkDodo Oooops, my apologies. I naively assumed it's v3.3.3 only.

Okay, if that's the case, it's probably something called context-sensitive function, which can't be solved on our end. It's TS issue/limitation.

If anybody has a real fix or some investigations, please jump in. For now, let me close this issue as a know limitation.

**Comment by timothyallan** [comment] 2021-04-12 19:29
I'm not a TS guru, but I know that MobX handles this somehow with their `reaction`. It's able to infer the returning property of what you specify in the selector. https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/core/reaction.ts

**Comment by dai-shi** [comment] 2021-04-12 22:28
Let's reopen this and see someone can tackle it.

**Comment by dai-shi** [comment] 2021-07-10 08:26
marked it as typing enhancement. (i'm not sure if it's possible.)

**Comment by vlad-zhukov** [comment] 2021-07-19 04:57
Type inference doesn't work in this case because at the time `listener` types resolve, `selector` types hasn't been resolved yet and `StateSlice` is `unknown`.

The "fixes" I am aware of are either swap arguments order

```
subscribe(selector, listener, equalityFn)
```

or use on object instead of separate arguments

```
subscribe({ selector, listener, equalityFn })
```

**Comment by dai-shi** [comment] 2021-07-19 06:11
Yeah, when I played with (struggled with) #428, I noticed that if we had the arguments swapped, it would have been possible.

@vlad-zhukov Thanks for your comment. We are not going to change the api only for types, so let's close this as not fixable.

**Closed by dai-shi** 2021-07-19 06:11 UTC
Labels: enhancement, help wanted, typescript
