### ISSUE TITLE
State value doesn't seem to persist for a Select element (dropdown)

### ISSUE THREAD

**Issue by moh-altimimi** [pmndrs/zustand#529] opened 2021-08-09 11:19 UTC
Hi

I have a very simple example (in Next JS) that doesn't seem to work, where I have created a basic store:

```javascript
interface IAppState {
    team: ETeam | undefined;
    layout: "List" | "Field";
    setTeam: (t: ETeam) => void;
    setLayout: (s: "List" | "Field") => void;
}

export const useStore = create<IAppState>(persist(
    (set) => ({
        team: undefined,
        layout: "List",
        setTeam: (t) => set({team: t}),
        setLayout: (s) => set({layout: s}),
    }),
    {
        name: "my-team-list",
        getStorage: () => localStorage,
    }
))
```

Then I'm using it as follows (simplified)

```javascript
export const Main = () => {
    const { team, setTeam } = useStore(state => state);

    return {
        <h1>{team}</h1> // returns persisted state correctly

        <select value={team} onChange={(opt) => setTeam(opt => opt.target.value as ETeam)}>
            <option value={ETeam.Bulldogs}>Bulldogs</option>
            <option value={ETeam.Broncos}>Broncos</option>
            <option value={ETeam.Cowboys}>Cowboys</option>            
            // etc
        <select>
    }
}
```

In the H1 element, the value is correct - in the select it always defaults back to the first option of the select - regardless of the value in localStorage.

Have I missed something?

Appreciate any help!

**Comment by AnatoleLucet** [comment] 2021-08-09 14:06
Hi, you're giving a function (`opt => opt.target.value as ETeam`) as the `t` argument of `setTeam` while it should match the `ETeam` enum.
Your `onChange` handler should look something like this:
```jsx
onChange={opt => setTeam(opt.target.value)}
```
See: https://stackblitz.com/edit/nextjs-klqzyh?file=pages%2Findex.tsx

**Comment by moh-altimimi** [comment] 2021-08-13 04:52
Hi @AnatoleLucet - thanks for the response, but this was a typo on my behalf when I was writing the example.

In my actual code, I have as you have above for the onChange handler.

Any other ideas?

Thanks

**Comment by AnatoleLucet** [comment] 2021-08-13 11:14
Well I'm really not sure. I seems to work on the sandbox I sent.
What version are you using?

Could you try to reproduce the bug in a new, minimal, nextjs projet (e.g. in a codesandbox)?

**Comment by moh-altimimi** [comment] 2021-08-14 13:12
Hello again @AnatoleLucet - your sandbox does exactly what I described, which is unexpected.

Say I select "Broncos", which is index 1 so the <h1> has the value 1.

When I reload, that value remains 1, as expected. But the select element value is "Bulldogs", the first option of the select, no matter what.

**Comment by AnatoleLucet** [comment] 2021-08-14 14:59
Ah! My bad, I see now.

On your original example, if I change the onChange handler to `onChange={opt => setTeam(+opt.target.value)}` to make sure the stored team is a number (which it wasn't) to match the enum's index, it still doesn't work.
But if I change the value to something like `value={JSON.parse('{"team":1}').team}` to grossly simulate `persist`'s deserialization, it does work. See: https://stackblitz.com/edit/nextjs-bxdt5c?file=pages%2Findex.tsx

I'm not sure to understand what's going on here. I'll investigate a bit later.

**Comment by chornos13** [comment] 2021-09-11 03:31
You don't need to use "useEffect",
I think the issue is because server side rendering (next.js) in this case. but you can simply fix this issue by safely render select element when it's ready to render on client side because you read value from localStorage (which is only available on client side) by giving condition like this


```jsx
    <Fragment>
      <h1>{team}</h1>
      Safely Render:
      {typeof window !== 'undefined' && (
        <select value={team} onChange={opt => setTeam(opt.target.value)}>
          <option value={ETeam.Bulldogs}>Bulldogs</option>
          <option value={ETeam.Broncos}>Broncos</option>
          <option value={ETeam.Cowboys}>Cowboys</option>
          // etc
        </select>
      )}
      <br />
      <br />
      Regular Render:
      <select value={team} onChange={opt => setTeam(opt.target.value)}>
        <option value={ETeam.Bulldogs}>Bulldogs</option>
        <option value={ETeam.Broncos}>Broncos</option>
        <option value={ETeam.Cowboys}>Cowboys</option>
        // etc
      </select>
    </Fragment>
```
![image](https://user-images.githubusercontent.com/20974979/132934856-4fa85b94-0d9b-4d04-91ad-a517f18823e5.png)

**Comment by AnatoleLucet** [comment] 2021-11-22 13:23
Looks like @chornos13 is right, it apparently *is* an issue with SSR.
I'll close this for now.

**Closed by AnatoleLucet** 2021-11-22 13:23 UTC
Labels: middleware/persist
