### ISSUE TITLE
Zustand module bundling problems

### ISSUE THREAD

**Issue by jorekai** [pmndrs/zustand#454] opened 2021-06-23 12:15 UTC
Hey, I am building private modules for an application, which are shared through workspaces.
 When using the build library in my ejected react-app i run into difficulties.
 Something with the default export of zustand's create method is not working with my rollup/create-react-app configurations.
 I have no clue if this error is produced by zustand or rollup or CRA/webpack. 
Any help is appreciated.

The error:

![image](https://user-images.githubusercontent.com/15143394/123092908-46b6cf00-d42b-11eb-89a6-962766df3005.png)

The typescript source file which must be bundled (lib/src/stores.ts):

```typescript
import { KitaModel } from "../utils/apiModels";
import create from "zustand";

export class Kita {...}
export interface KitaStore {...}
export const useKitaStore = create<KitaStore>((set) => ({...}));
```

The resulting type declarations (lib/dist/stores.d.ts):

```typescript
import { KitaModel } from "../utils/apiModels";

export declare class Kita {...}
export interface KitaStore {...}
export declare const useKitaStore: import("zustand").UseStore<KitaStore>;
```

The rollup config (lib/rollup.config.js):

```typescript
import pkg from './package.json';
import resolve from '@rollup/plugin-node-resolve';
import { terser } from 'rollup-plugin-terser';
import typescript from 'rollup-plugin-typescript2';

export default {
	preserveSymlinks: true,
	input: 'src/index.ts',
	output: [{
		format: 'esm',
		file: pkg.module,
		sourcemap: false,
	}, {
		format: 'cjs',
		file: pkg.main,
		sourcemap: false,
	},
	{
		name: pkg['umd:name'] || pkg.name,
		format: 'umd',
		file: pkg.unpkg,
		sourcemap: false,
		plugins: [
			terser()
		],
	}],
	external: [
		...require('module').builtinModules,
		...Object.keys(pkg.dependencies || {}),
		...Object.keys(pkg.peerDependencies || {}),
	],
	plugins: [
		resolve(),
		typescript()
	]
}
```

The ts config (lib/tsconfig.json)

```typescript
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es6",                                /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', 'ES2021', or 'ESNEXT'. */
    "module": "es6",                           /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */                          /* Report errors in .js files. */
    "jsx": "react",                           /* Specify JSX code generation: 'preserve', 'react-native', 'react', 'react-jsx' or 'react-jsxdev'. */
    "declaration": true,                         /* Generates corresponding '.d.ts' file. */
    "sourceMap": true,                           /* Generates corresponding '.map' file. */
    "outDir": "./dist",                              /* Redirect output structure to the directory. */
    "rootDir": "./",                             /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    /* Strict Type-Checking Options */
    "strict": true,                                 /* Enable all strict type-checking options. */
    "noImplicitAny": true,                       /* Raise error on expressions and declarations with an implied 'any' type. */
    "alwaysStrict": true,                        /* Parse in strict mode and emit "use strict" for each source file. */
    /* Module Resolution Options */
    "moduleResolution": "node",                  /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./",                             /* Base directory to resolve non-absolute module names. */
    "esModuleInterop": true,                        /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    /* Advanced Options */
    "skipLibCheck": true,                           /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true        /* Disallow inconsistently-cased references to the same file. */
  },
  "include": ["src/*", "@types/*"],
  "exclude": ["node_modules"]
}
```
The package.json (lib/package.json)

```typescript
{
  "version": "1.0.0",
  "description": "private shared utility library",
  "module": "dist/index.mjs",
  "unpkg": "dist/index.min.js",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "npx rollup -c"
  },
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    },
    "./package.json": "./package.json"
  },
  "keywords": [],
  "license": "ISC",
  "dependencies": {
    "@types/node": "^15.12.4",
    "axios": "^0.21.1",
    "typescript": "^4.3.4",
    "zustand": "^3.5.4"
  },
  "devDependencies": {
    "@rollup/plugin-node-resolve": "8.1.0",
    "rollup": "2.21.0",
    "rollup-plugin-terser": "6.1.0",
    "rollup-plugin-typescript2": "0.27.1"
  }
}
```

The imports/exports in my dist bundle (lib/dist/index.m.js):

````typescript
...
import create from 'zustand';
...
export { ..., useKitaStore };
```

**Comment by dai-shi** [comment] 2021-07-10 08:15
Is this fixed in v3.5.6?

**Comment by jorekai** [comment] 2021-07-11 17:33
I upgraded my zustand dependency and rebuild the whole library. It still does not seem to work, however i can fix it with a workaround as follows:

change the following declaration of the bundled method in index.mjs to use `zustand.default(...)` instead of `zustand(...)`

(produces error)
```typescript
const useKitaStore = zustand((set) => ({
    store: [],
    setStore: (newKitas) => set({ store: newKitas || [] }),
}));
```

(works as expected)
```typescript
const useKitaStore = zustand.default((set) => ({
    store: [],
    setStore: (newKitas) => set({ store: newKitas || [] }),
}));
```

 I cannot trace the problem coming from zustand itself, it can also be a problem with my rollup setup. I can see this being related to #334.

**Comment by dai-shi** [comment] 2021-07-11 21:58
hmm, sounds like mjs is picking cjs bundle. this seems like an issue that could have solved with v3.5.6. Maybe we fail to fix #334 too? 😕

**Comment by barelyhuman** [comment] 2021-07-22 08:22
Mind if I pick it up?

**Comment by dai-shi** [comment] 2021-07-22 08:25
Please go ahead.

**Comment by barelyhuman** [comment] 2021-07-22 08:53
@jorekai Hey, 
is it possible for you to replicate this into a dummy repository ? 
Here's the things I need to go through
- the tsconfig / rollup config 
- and example bundle of the library you are trying to create, just using zustand 
- the package.json of both the packages in your monorepo 
- How is react importing this , so the webpack config

basically if you can create the above bundling issue with a reproducible repo, it'd help a lot 

On the other hand, just to check, if you react app's package.json of type:"module" or not? if you can clarify that

**Comment by barelyhuman** [comment] 2021-07-22 16:52
@dai-shi Hey, got caught up in office work, 
I'll be raising a PR but please don't merge it right now. 

I would like it to be tested on multiple bundlers before we merge it. 
Specifically Rollup and Webpack since they have 2 different ways to resolve esm modules. 


@jorekai Hey, once the PR is raised, there will be codesandbox link generated on the PR, can you use that generated codesandbox to test out your issue? 
also if possible trying installing the specific branch as an npm dependency (though you'll have to manually build the package post installation)

**Comment by jorekai** [comment] 2021-07-23 09:48
I will give you feedback once i find the time to test it out. I should be able to do so over the next 2 days. Thank you for looking into it. @barelyhuman

**Comment by barelyhuman** [comment] 2021-07-24 07:47
@jorekai 
here's the version I want you to test 
`yarn add https://pkg.csb.dev/barelyhuman/zustand/commit/b0f2ee34/zustand`

@dai-shi if he can confirm we are basically done with the issue since it works on all other sandboxes at this point. 

the above was generated and can be tested on https://github.com/barelyhuman/zustand/pull/3

**Comment by jorekai** [comment] 2021-07-24 12:01
So i did a complete rebuild on my project and changed my zustand dependency to rely on your build @barelyhuman `https://pkg.csb.dev/barelyhuman/zustand/commit/b0f2ee34/zustand`.

Somehow i am still running into the original issue but i got additional errors now.

![image](https://user-images.githubusercontent.com/15143394/126864949-b8787667-b668-4bbf-8eae-9899a86c4ee1.png)

I created a minimum example you can clone here: https://github.com/jorekai/reproducible-error-zustand.git 

I hope this is helpful for you @barelyhuman

**Comment by barelyhuman** [comment] 2021-07-24 12:25
@jorekai  yeah that was helpful, when you said ejected app I though you had something like a custom setup like rewired, I failed to take the basic approach of the default ejected cra... 

the solution to your problem isn't with zustand but we ended up fixing zustand anyway so the next line will help you.


add the bottom object to your `webpack.config.js` under the `rules` array:
```
{
          type: "javascript/auto",
          test: /\.mjs$/,
          use: [],
        },
```

Should solve your issue :)

**Comment by jorekai** [comment] 2021-07-24 12:33
Indeed this fixes the issue. Thanks for the effort, I think this can be closed.

**Comment by barelyhuman** [comment] 2021-07-24 12:34
As for why this works and while you can force esm by changing the above to `javascript/esm` it'll fail since React doesn't support esm and so you get issues like below
```sh
../lib/dist/index.mjs
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
```

You can use esm react replacements like https://www.npmjs.com/package/@pika/react and https://www.npmjs.com/package/@pika/react-dom but this is the simplest way out right now.

Hope that helps

**Comment by barelyhuman** [comment] 2021-07-24 12:35
@dai-shi You can close this, I'll update the draft PR with the changes I made in a few minutes.

**Closed** 2021-07-24 12:47 UTC
Labels: help wanted
