### ISSUE TITLE
Type error when using interface instead of type in Typescript

### ISSUE THREAD

**Issue by rosostolato** [pmndrs/zustand#213] opened 2020-10-21 23:48 UTC
Typescript is throwing error when I use interface instead of type. Take this example:

```ts
export interface DashboardSummary {
  added: number
  updated: number
  active: number
  invite: number
}

const initialState: DashboardSummary = {
  invite: 0,
  active: 0,
  added: 0,
  updated: 0,
}

const useDashboardStore = create(
  combine(initialState, set => ({ // error on `initialState`
    fetch: async () => {
      const res = await axios.get<DashboardSummary>('/api/user/dashboard')

      if (res.status === 200) {
        set(res.data) // error on `res.data`
      }
    },
  }))
)
```

On hover `initialState`, typescript says:
```
Argument of type 'DashboardSummary' is not assignable to parameter of type 'Record<string | number | symbol, unknown>'.
  Index signature is missing in type 'DashboardSummary'.ts(2345)
```

Is it possible to fix it?

**Comment by dai-shi** [comment] 2020-10-22 00:11
duplicate of #183 

Maybe we could write a small note in https://github.com/pmndrs/zustand#typescript. Anyone volunteer?

**Closed** 2021-01-07 22:55 UTC
Labels: good first issue, help wanted
