### ISSUE TITLE
TypeScript having issues with inferring the type of Provider

### ISSUE THREAD

**Issue by GitGangGuy** [pmndrs/zustand#473] opened 2021-06-30 13:20 UTC
Here's my `store.ts` file:
```typescript
import create, { UseStore } from 'zustand';
import createContext from 'zustand/context';

export const { Provider, useStore } = createContext();
export const createStore = (): UseStore<TodosState> => // ...
```
TypeScript is reporting an error when exporting Provider: `
The inferred type of 'Provider' cannot be named without a reference to '.pnpm/@types+react@17.0.11/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.` Where can I find a "clean" type annotation? The generated type annotations I was able to find from opening the type definition for Provider aren't very pretty.

**Comment by dai-shi** [comment] 2021-06-30 15:36
Is this reproducible in codesandbox? Could you create one?

**Comment by dai-shi** [comment] 2021-07-08 09:08
@GitGangGuy Would this the same or similar to #481?

**Comment by GitGangGuy** [comment] 2021-07-08 09:54
@dai-shi While the linked issue is also concerned with the pretty poor TypeScript signatures, it describes a different problem (the lacking type signature of `useStore` vs the TypeScript error when using `Provider`). I don't have a codesandbox reproduction rn, but it would be great if you could have a look at the fairly simple [to-do app repository](https://github.com/lsglab/Schuelerportal) where I experienced this issue. [This is the relevant file](https://github.com/lsglab/Schuelerportal/blob/trunk/src/store.ts#L9), and [this file](https://github.com/lsglab/Schuelerportal/blob/trunk/components/ZustandDemo.tsx#L23-L30) also showcases the pain of using `useStore` with TypeScript (#481). Thanks!

**Comment by dai-shi** [comment] 2021-07-08 10:50
So, it actually sounds like the root cause is the same. Let's see how it goes.

**Comment by dai-shi** [comment] 2021-07-08 12:52
@GitGangGuy Hi, would you try if #484 changes anything for you?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/484
Visit here and find "Local install instructions"

**Comment by dai-shi** [comment] 2021-07-30 12:52
Closing this assuming it's fixed. Let me know otherwise, and we can re-open.

**Closed by dai-shi** 2021-07-30 12:52 UTC
Labels: typescript
