### ISSUE TITLE
Multiple groups of checkboxes, optimize rerendering

### ISSUE THREAD

**Issue by dgastudio** [pmndrs/zustand#392] opened 2021-05-17 21:31 UTC
Hello, 

i have a complex structure of checkboxes
https://monosnap.com/file/y43SLkgElIVGD00QBimnF4hZdS9nzP

group of items with select all for each group

so, for now, on select any checkbox, all existing  checkboxes are rerendered

my checkbox component

`export default function TableCheckbox({row}) {
  const SelectedItems = useStore(state => state.SelectedItems)
  const SelectedItemsChange = useStore(state => state.SelectedItemsChange)

  let checked = SelectedItems.includes(row.uuid)
  return (
      <div style={{lineHeight: '46px'}}>
        <Checkbox
            value={row.uuid}
            checked={checked}
            onChange={() => {
              SelectedItemsChange([row.uuid])
            }}
            inline
        >
          {Math.random()}
        </Checkbox>
      </div>
  )
}`

my state
`      SelectedItems: [],
      SelectedItemsChange: (uuids) => {

        let selected = get().SelectedItems;
        uuids.map((uuid) =>
            selected.indexOf(uuid) === -1 ? selected.push(uuid) : selected.splice(uuid, 1)
        );

        set(state => ({
          SelectedItems: [...selected],
        }))
      },
`

any advice, about how can i optimize it?

thanks in advance

**Comment by dai-shi** [comment] 2021-05-17 21:53
You want to try this:
```js
  let checked = useStore(state => state.SelectedItems.includes(row.uuid))
```

Closing this. Feel free to continue discussion here or create a [new discussion](https://github.com/pmndrs/zustand/discussions/new).

**Closed by dai-shi** 2021-05-17 21:53 UTC

**Comment by dgastudio** [comment] 2021-05-17 21:56
Hello Dai-shi.
First of all, thank you for you response

i have applied your code, but all checkboxes are still rerendering.

basically, you have moved to lines of my code in one only.
so, state is still updating and checkboxes are still rerendering

**Comment by dgastudio** [comment] 2021-05-17 22:00
https://monosnap.com/file/oTSxqAdvyzyn2DRvPW7WBn7gOOVDTm

**Comment by dai-shi** [comment] 2021-05-17 22:28
I guess the rerendering is caused by other code.
Won't you create a small repro in codesandbox, and you can narrow down the problem.
It'd be easier for us to help too.
