### ISSUE TITLE
Wrong types on onRehydrateStorage 

### ISSUE THREAD

**Issue by TommySorensen** [pmndrs/zustand#872] opened 2022-03-16 11:10 UTC
Hi all

It seems like there is some inconsistent in the Typescript types on the persist function.

The `state` in the `onRehydrateStorage` does not know that the `reference` is optional from the create function, so i can't check for it.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/4134473/158576494-e971a76d-2366-494c-b094-a6e7a3ea0ad5.png">

```js
import create from 'zustand';
import { persist } from 'zustand/middleware';

const useBasketStore = create<BasketStore>(
    persist(
        (set) => ({
            setReference: (reference) => set({ reference }),
        }),
        {
            name: 'basket',
            onRehydrateStorage: () => async (state, error) => {
                console.log('hydration starts', state);

                if (error || !state) {
                    console.log('an error happened during hydration', error);
                } else if (state.reference) {
                    const { basketReference } = await createBasket();
                    state.setReference(basketReference);
                }
            },
        }
    )
);

type BasketStore = {
    reference?: string;
    setReference: (reference: string) => void;
};
```

Seems like a bug, or is there a way to set the state in the create function to avoid this issue?

**Comment by dai-shi** [comment] 2022-03-16 11:12
(Not instantly sure if this is an issue only in v3 or an issue that will exist in v4 too.)

**Comment by TommySorensen** [comment] 2022-03-16 11:26
I am using `v3.7.1`. I haven't checked with v4.

**Comment by TommySorensen** [comment] 2022-03-16 12:07
@dai-shi Just tried with your suggestion but same type error occurs
```js
create<
    BasketStore,
    SetState<BasketStore>,
    GetState<BasketStore>,
    Mutate<StoreApi<BasketStore>, [['zustand/persist', Partial<BasketStore>]]>
>
```

**Comment by dai-shi** [comment] 2022-03-16 12:11
Thanks for trying.
Then, I'm not sure if I understand the issue correctly.
Hope @AnatoleLucet or @devanshj can help.

**Comment by dai-shi** [comment] 2022-03-16 13:53
Aren't you using "strict": true in tsconfig.json?

**Comment by TommySorensen** [comment] 2022-03-16 14:20
@dai-shi Yes

```json
{
    "extends": "./tsconfig.paths.json",
    "compilerOptions": {
        "allowJs": true,
        "alwaysStrict": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "lib": ["dom", "es2017"],
        "module": "esnext",
        "moduleResolution": "node",
        "noEmit": true,
        "noFallthroughCasesInSwitch": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "strict": true,
        "target": "esnext",
        "types": ["node", "jest"]
    },
    "exclude": ["node_modules"],
    "include": ["src/**/*.ts", "src/**/*.tsx", "**/*.d.ts", "./jest.setup.ts"]
}

**Comment by AnatoleLucet** [comment] 2022-03-16 21:10
Seems to be an issue with the new type system.
@TommySorensen you should be able to fix it by giving `BasketStore` to `persist`.
```ts
const useBasketStore = create<BasketStore>(
    persist<BasketStore>(
        // ...
    )
);
```

**Comment by TommySorensen** [comment] 2022-03-16 21:13
Ahh great. Thx @AnatoleLucet 👍 Closing issue then.

**Comment by devanshj** [comment] 2022-03-16 21:31
Imo let's keep this opened, as it's not resolved only a workaround has been found. (Keeping it open will also serve as a reminder for me to look into it or else I might forget.)

**Comment by dai-shi** [comment] 2022-03-17 02:35
Thanks guys.
@devanshj Hope you find a solution!

**Comment by devanshj** [comment] 2022-03-27 17:15
The problem is the `BasketStore` passed as a type parameter to `create` doesn't get propagated to `persist`. If you hover on `persist` you'll see that the `S` (state) type parameter is inferred as `{ setReference: (reference: string) => void }` (instead of `BasketStore`) based on the initial state...

![image](https://user-images.githubusercontent.com/30295578/160292641-40a33a1a-ebb2-4068-9cf3-f1373fc3735b.png)

The fix is trivial that is (as @AnatoleLucet said) to pass `BasketStore` as a type parameter to `persist` too ie `persist<BasketStore>(...)`: https://tsplay.dev/NBj2gN

In v4 there's no need to pass the type parameter to persist as the one passed in `create` will get propagated all the way down.

(We can close this now)

**Comment by dai-shi** [comment] 2022-03-27 22:29
Thanks for the explanation!

**Closed by dai-shi** 2022-03-27 22:29 UTC
Labels: middleware/persist
