### ISSUE TITLE
Expected server HTML to contain a matching xxx

### ISSUE THREAD

**Issue by dpyzo0o** [pmndrs/zustand#702] opened 2021-12-08 10:08 UTC
I'm using zustand with Remix, if I use the persist middleware there will be an error:

<img width="713" alt="Screen Shot 2021-12-08 at 6 05 29 PM" src="https://user-images.githubusercontent.com/24768249/145189331-021fa901-3281-4b25-b57a-1e3d50b0dc81.png">

The error comes from these lines 
<img width="585" alt="Screen Shot 2021-12-08 at 6 07 15 PM" src="https://user-images.githubusercontent.com/24768249/145189582-05636490-a97a-4c80-becd-9b6deafefef5.png">

The `todosCount` comes from zustand store. Any ideas?

**Comment by AnatoleLucet** [comment] 2021-12-08 12:36
Looks like a React hydration mismatch. Probably a duplicate of #324.
But in short: you're only rendering the `span` and `Footer` on the client because `todosCount` comes from the storage and (I assume) will be null-ish on a server environment. Remix/React is complaining because the html rendered by the server mismatches the one rendered on the client.

See [this comment](https://github.com/pmndrs/zustand/issues/324#issuecomment-799215374) for one way to fix it.

**Closed** 2021-12-08 13:27 UTC
Labels: middleware/persist
