### ISSUE TITLE
Using devtools for multiple stores

### ISSUE THREAD

**Issue by israelalagbe** [pmndrs/zustand#355] opened 2021-04-09 09:11 UTC
At the moment, I tried using the devtool for multiple stores, it seems it can only work for a single store at a time.

**Comment by dai-shi** [comment] 2021-04-09 13:10
Does putting "prefix" solve it?
https://github.com/pmndrs/zustand#redux-devtools

**Comment by israelalagbe** [comment] 2021-04-09 13:13
@dai-shi 
No it didn't, I tried that too.

**Comment by dai-shi** [comment] 2021-04-09 13:21
Hmm, I'm not sure then. Can anyone help?

**Comment by dai-shi** [comment] 2021-04-09 23:17
> in fact each zustand store will have its own redux devtools page

Hmm, I thought it's by design. If you want a single store like redux, why won't you create a single zustand store?

**Comment by olavoparno** [comment] 2021-04-20 00:31
@dai-shi precisely. I don't know if it would be better if it was explained in the docs this difference from redux store when using devtools so that it wouldn't be misunderstood.

**Comment by dai-shi** [comment] 2021-04-20 00:35
> each zustand store will have its own redux devtools page

So, explain this in the readme? Mind opening a PR?

**Comment by olavoparno** [comment] 2021-04-20 00:39
I might do it later this week

**Comment by olavoparno** [comment] 2021-04-20 19:49
> > each zustand store will have its own redux devtools page
> 
> So, explain this in the readme? Mind opening a PR?

here it is, https://github.com/pmndrs/zustand/pull/369

**Comment by dai-shi** [comment] 2021-05-05 15:15
closed by #369

**Closed by dai-shi** 2021-05-05 15:15 UTC
